### ISSUE TITLE
fedora-podman connection issue

### ISSUE THREAD

**Issue by willcohen** [afbjorklund/fedora-lima#1]
Is there something you're doing outside of your readme for the connection? When I try to add a lima and lima-root connection via the port listed in `limactl list`, ssh isn't able to make the connection:

```
$ podman system connection add --default lima ssh://127.0.0.1:61974
Error: failed to connect: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

**Comment by afbjorklund** [comment]
The port will be random, but compare with `limactl --debug shell fedora-podman` logging and the "executing ssh" ?

Also, if you don't copy your pubkeys you might need to add the --identity of `~/.lima/_config/user` to the connection.

```yaml
ssh:
  # Load ~/.ssh/*.pub in addition to $LIMA_HOME/_config/user.pub .
  # This option is useful when you want to use other SSH-based
  # applications such as rsync with the Lima instance.
  # If you have an insecure key under ~/.ssh, do not use this option.
  # Default: true
  loadDotSSHPubKeys: true
```

If you don't have any ssh agent and no ssh keys, I suppose it will fail... Will add the default identity to the README
